networks:
  otel-demo:
    name: otel-demo
    driver: bridge

services:
  jaeger:
    image: jaegertracing/jaeger:2.14.0
    ports:
      - "16686:16686"   # Jaeger UI
    networks:
      - otel-demo

  collector:
    image: otel/opentelemetry-collector:0.144.0
    command: ["--config=/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yaml:/otel-collector.yaml:ro
    ports:
      - "4317:4317"     # OTLP gRPC
    depends_on:
      - jaeger
    networks:
      - otel-demo

  ctfd:
    image: ctferio/ctfd:3.8.2-0.9.0
    ports:
      - "8000:8000"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "dns://collector:4317"
      OTEL_EXPORTER_OTLP_INSECURE: "true"
    depends_on:
      - collector
    networks:
      - otel-demo
    healthcheck:
      test: python3 -c 'import requests; requests.get("http://localhost:8000")'
      interval: 10s
      retries: 3
      timeout: 10s

  ctfd-setup:
    image: ctferio/ctfd-setup:v1.7.3@sha256:735a9b56747b901d00a9e9d78715c3ceee067828f5dc38bf08d79b8d07a028c0
    environment:
      URL: http://ctfd:8000
      FILE: /.ctfd.yaml
    volumes:
      - .ctfd.yaml:/.ctfd.yaml
    networks:
      - otel-demo
    depends_on:
      ctfd:
        condition: service_healthy
